version: 2.1
jobs:
  build: # runs not using `Workflows` must have a `build` job as entry point
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          # run our tests using xcode's cli tool `xcodebuild`
          name: cmake
          command: mkdir build && cmake -DUSE_JUICE=1 -DUSE_GNUTLS=0 .. && make
